HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# Use vi mode
bindkey -v

# Path to your oh-my-zsh installation.
export ZSH="/home/gaston/.oh-my-zsh"
export ZSH_GLOBAL="/usr/share/zsh"

# The following lines were added by compinstall
zstyle :compinstall filename '/home/gaston/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="bira"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions shrink-path zsh-history-substring-search zsh-vim-mode) 

source $ZSH/oh-my-zsh.sh
# source <(minikube completion zsh)
# source <(kubectl completion zsh)
# source <(helm completion zsh)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=137,underline'

# To re-bind widgets, run `_zsh_autosuggest_bind_widgets`.
ZSH_AUTOSUGGEST_MANUAL_REBIND=1

#########################
# PLUGINS CONFIGURATION #
#########################
# zsh-history-substring-search config
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='fg=137,underline'
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND=''

# zsh-vim-mode configuration
MODE_INDICATOR_VIINS='-- INSERT --'
MODE_INDICATOR_VICMD='-- NORMAL --'
MODE_INDICATOR_REPLACE='-- REPLACE --'
MODE_INDICATOR_SEARCH='-- SEARCH --'
MODE_INDICATOR_VISUAL='-- VISUAL --'
MODE_INDICATOR_VLINE='-- V-LINE --'
RPROMPT='%B${return_code}%b ${MODE_INDICATOR_PROMPT} [%T]'
KEYTIMEOUT=1
VIM_MODE_INITIAL_KEYMAP=last

# Source commonrc
source ~/.commonrc

# auto-generated by kdesrc-build initial setup: do not remove!
export PATH="$HOME/Development/kde/src/kdesrc-build:$PATH"
kdesrc-run ()
{
  source "$HOME/Development/kde/build/$1/prefix.sh" && "$HOME/Development/kde/usr/bin/$1"
}
